---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "REMnux: A Linux Toolkit for Reverse-Engineering and Analyzing Malware"
keywords:    "REMnux, malware analysis, reverse-engineering, malicious software, tools, utilities"
description: "REMnux is lightweight toolkit for assisting malware analysts with reverse-engineering malicious software."
source_link: "https://github.com/REMnux/REMnux.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  
